/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'operator' : null } |
  { 'shopper' : null } |
  { 'driver' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Article {
  'id' : string,
  'categoryId' : string,
  'title' : string,
  'body' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'imagesJson' : [] | [string],
  'authorPrincipal' : Principal,
}
export interface ArticleCategory { 'id' : string, 'name' : string }
export interface BusinessArea {
  'id' : string,
  'name' : string,
  'townId' : string,
  'areaType' : string,
}
export interface LikeDislike {
  'userId' : Principal,
  'isLike' : boolean,
  'targetType' : string,
  'targetId' : string,
}
export interface NomayiniBalance {
  'totalEarned' : number,
  'unlockedBalance' : number,
  'lockedLongTerm' : number,
  'lockedShortTerm' : number,
}
export interface NomayiniTransaction {
  'id' : string,
  'unlockDate' : [] | [string],
  'date' : string,
  'description' : string,
  'txType' : string,
  'amount' : number,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'driverId' : [] | [string],
  'isWalkIn' : boolean,
  'total' : number,
  'customerPhone' : string,
  'pickupPointId' : string,
  'pickupPointName' : string,
  'dedicatedRetailerId' : [] | [string],
  'createdAt' : string,
  'deliveryType' : string,
  'deliveryAreasJson' : [] | [string],
  'parentOrderId' : [] | [string],
  'updatedAt' : string,
  'homeAddress' : [] | [string],
  'shopperId' : [] | [string],
  'townId' : string,
  'customerId' : string,
  'itemsJson' : string,
  'driverName' : [] | [string],
  'businessAreaId' : string,
  'shopperName' : [] | [string],
}
export interface OrderExtended {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'driverId' : [] | [string],
  'isWalkIn' : boolean,
  'shopperProofImagesJson' : [] | [string],
  'total' : number,
  'customerPhone' : string,
  'pickupPointId' : string,
  'pickupPointName' : string,
  'dedicatedRetailerId' : [] | [string],
  'createdAt' : string,
  'deliveryType' : string,
  'deliveryAreasJson' : [] | [string],
  'parentOrderId' : [] | [string],
  'updatedAt' : string,
  'homeAddress' : [] | [string],
  'shopperId' : [] | [string],
  'townId' : string,
  'customerId' : string,
  'itemsJson' : string,
  'driverName' : [] | [string],
  'businessAreaId' : string,
  'shopperName' : [] | [string],
}
export interface PickupPoint {
  'id' : string,
  'name' : string,
  'townId' : string,
  'address' : string,
  'profileImageUrl' : [] | [string],
}
export interface ProductExtended {
  'id' : string,
  'suggestedBy' : [] | [string],
  'inStock' : boolean,
  'isSuggestion' : boolean,
  'name' : string,
  'description' : string,
  'imageEmoji' : string,
  'serviceFee' : number,
  'approved' : boolean,
  'category' : string,
  'imagesJson' : [] | [string],
  'isSpecial' : boolean,
}
export interface ProductListing {
  'id' : string,
  'productId' : string,
  'outOfStock' : boolean,
  'price' : number,
  'retailerId' : string,
}
export interface RetailerExtended {
  'id' : string,
  'name' : string,
  'parentRetailerId' : [] | [string],
  'operatingHoursJson' : [] | [string],
  'townId' : string,
  'address' : string,
  'businessAreaId' : string,
}
export interface RetailerProductExtended {
  'id' : string,
  'availableColors' : [] | [string],
  'inStock' : boolean,
  'outOfStockColors' : [] | [string],
  'name' : string,
  'description' : string,
  'inheritedFrom' : [] | [string],
  'outOfStockSizes' : [] | [string],
  'outOfStockFlavors' : [] | [string],
  'imageEmoji' : string,
  'availableWeights' : [] | [string],
  'availableSizes' : [] | [string],
  'category' : string,
  'price' : number,
  'imagesJson' : [] | [string],
  'retailerId' : string,
  'availableFlavors' : [] | [string],
  'outOfStockWeights' : [] | [string],
}
export interface Review {
  'id' : string,
  'createdAt' : bigint,
  'reviewerId' : Principal,
  'orderId' : string,
  'comment' : string,
  'targetType' : string,
  'rating' : bigint,
  'targetId' : string,
}
export interface Town { 'id' : string, 'province' : string, 'name' : string }
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'role' : AppUserRole,
  'phone' : string,
  'registrationStatus' : { 'active' : null } |
    { 'pending' : null } |
    { 'updateNeeded' : null } |
    { 'rejected' : null },
  'registeredAt' : bigint,
  'businessAreaId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addArticle' : ActorMethod<
    [string, string, string, string, [] | [string], boolean],
    undefined
  >,
  'addArticleCategory' : ActorMethod<[string, string], undefined>,
  'addBusinessArea' : ActorMethod<[string, string, string, string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'addListing' : ActorMethod<[string, string, string, number], undefined>,
  'addPickupPoint' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'addProduct' : ActorMethod<
    [string, string, string, string, string, [] | [string], boolean, number],
    undefined
  >,
  'addRetailer' : ActorMethod<
    [string, string, string, string, string, [] | [string]],
    undefined
  >,
  'addRetailerProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'addReview' : ActorMethod<
    [string, string, string, bigint, string, string],
    undefined
  >,
  'addShopperProof' : ActorMethod<[string, string], undefined>,
  /**
   * / *********************************************************
   * /    * Persistence API Endpoints
   * /   ***********************************************************
   */
  'addTown' : ActorMethod<[string, string, string], undefined>,
  'approveSuggestion' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignShopperToRetailer' : ActorMethod<[Principal, string], undefined>,
  'deleteArticle' : ActorMethod<[string], undefined>,
  'deleteArticleCategory' : ActorMethod<[string], undefined>,
  'deleteBusinessArea' : ActorMethod<[string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteListing' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'deletePickupPoint' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteProductAttributes' : ActorMethod<[string], undefined>,
  'deleteRetailer' : ActorMethod<[string], undefined>,
  'deleteRetailerProduct' : ActorMethod<[string], undefined>,
  'deleteTown' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'exportRetailerToTown' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'getAllNomayiniBalances' : ActorMethod<[], Array<[string, NomayiniBalance]>>,
  'getAllShopperAssignments' : ActorMethod<
    [],
    Array<[Principal, Array<string>]>
  >,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getArticleCategories' : ActorMethod<[], Array<ArticleCategory>>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getBusinessAreas' : ActorMethod<[], Array<BusinessArea>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getLikesDislikesForTarget' : ActorMethod<[string], Array<LikeDislike>>,
  'getListings' : ActorMethod<[], Array<ProductListing>>,
  'getMyDriverOrders' : ActorMethod<[], Array<OrderExtended>>,
  'getMyOrders' : ActorMethod<[string], Array<OrderExtended>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyShopperOrders' : ActorMethod<[], Array<OrderExtended>>,
  'getNomayiniBalance' : ActorMethod<[], NomayiniBalance>,
  'getNomayiniTransactions' : ActorMethod<[], Array<NomayiniTransaction>>,
  'getOrderById' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<OrderExtended>>,
  'getOrdersByArea' : ActorMethod<[string], Array<OrderExtended>>,
  'getOrdersByCustomerId' : ActorMethod<[string], Array<OrderExtended>>,
  'getOrdersByPickupPoint' : ActorMethod<[string], Array<OrderExtended>>,
  'getOrdersByStatus' : ActorMethod<[string], Array<OrderExtended>>,
  'getPickupPoints' : ActorMethod<[], Array<PickupPoint>>,
  'getProductAttributes' : ActorMethod<[], Array<[string, string]>>,
  'getProducts' : ActorMethod<[], Array<ProductExtended>>,
  'getRetailerProductOosOptions' : ActorMethod<
    [string],
    {
      'outOfStockColors' : [] | [string],
      'outOfStockSizes' : [] | [string],
      'outOfStockFlavors' : [] | [string],
      'outOfStockWeights' : [] | [string],
    }
  >,
  'getRetailerProducts' : ActorMethod<[], Array<RetailerProductExtended>>,
  'getRetailers' : ActorMethod<[], Array<RetailerExtended>>,
  'getReviewsForTarget' : ActorMethod<[string], Array<Review>>,
  'getShopperRetailerIds' : ActorMethod<[Principal], Array<string>>,
  'getStaffBusinessArea' : ActorMethod<[Principal], [] | [string]>,
  'getTowns' : ActorMethod<[], Array<Town>>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'placeOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      [] | [string],
      string,
      boolean,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'registerUser' : ActorMethod<
    [AppUserRole, string, string, [] | [string]],
    undefined
  >,
  'rejectSuggestion' : ActorMethod<[string], undefined>,
  'renameCategory' : ActorMethod<[string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
  'sendNomayiniTokens' : ActorMethod<[string, number, string], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setLikeDislike' : ActorMethod<[string, string, boolean], undefined>,
  'setListingStock' : ActorMethod<[string, boolean], undefined>,
  'setProductAttributes' : ActorMethod<[string, string], undefined>,
  'setRetailerProductAttributeStock' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [string], [] | [string]],
    undefined
  >,
  'setRetailerProductStock' : ActorMethod<[string, boolean], undefined>,
  'suggestProduct' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'unassignShopperFromRetailer' : ActorMethod<[Principal, string], undefined>,
  'updateArticle' : ActorMethod<
    [string, string, string, string, [] | [string], boolean],
    undefined
  >,
  'updateArticleCategory' : ActorMethod<[string, string], undefined>,
  'updateCategories' : ActorMethod<[Array<string>], undefined>,
  'updateListingPrice' : ActorMethod<[string, number], undefined>,
  'updateOrderStatus' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      string,
    ],
    undefined
  >,
  'updatePickupPoint' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [string, string, string, string, string, [] | [string], boolean, number],
    undefined
  >,
  'updateRetailerHours' : ActorMethod<[string, string], undefined>,
  'updateRetailerProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'wipeAllNomayini' : ActorMethod<[], undefined>,
  'wipeAllOrders' : ActorMethod<[], undefined>,
  'wipeAllUsers' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];