/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    principal: Principal;
    displayName: string;
    role: AppUserRole;
    phone: string;
    registrationStatus: Variant_active_pending_updateNeeded_rejected;
    registeredAt: bigint;
    businessAreaId?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Town {
    id: string;
    province: string;
    name: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface RetailerProduct {
    id: string;
    inStock: boolean;
    name: string;
    description: string;
    imageEmoji: string;
    category: string;
    price: number;
    imagesJson?: string;
    retailerId: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: string;
    customerName: string;
    status: string;
    driverId?: string;
    isWalkIn: boolean;
    total: number;
    customerPhone: string;
    pickupPointId: string;
    pickupPointName: string;
    dedicatedRetailerId?: string;
    createdAt: string;
    deliveryType: string;
    deliveryAreasJson?: string;
    parentOrderId?: string;
    updatedAt: string;
    homeAddress?: string;
    shopperId?: string;
    townId: string;
    customerId: string;
    itemsJson: string;
    driverName?: string;
    businessAreaId: string;
    shopperName?: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ProductListing {
    id: string;
    productId: string;
    outOfStock: boolean;
    price: number;
    retailerId: string;
}
export interface BusinessArea {
    id: string;
    name: string;
    townId: string;
    areaType: string;
}
export interface PickupPoint {
    id: string;
    name: string;
    townId: string;
    address: string;
    profileImageUrl?: string;
}
export interface Product {
    id: string;
    suggestedBy?: string;
    inStock: boolean;
    isSuggestion: boolean;
    name: string;
    description: string;
    imageEmoji: string;
    approved: boolean;
    category: string;
    imagesJson?: string;
}
export interface Retailer {
    id: string;
    name: string;
    operatingHoursJson?: string;
    townId: string;
    address: string;
    businessAreaId: string;
}
export enum AppUserRole {
    admin = "admin",
    customer = "customer",
    operator = "operator",
    shopper = "shopper",
    driver = "driver"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_pending_updateNeeded_rejected {
    active = "active",
    pending = "pending",
    updateNeeded = "updateNeeded",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBusinessArea(id: string, name: string, townId: string, areaType: string): Promise<void>;
    addListing(id: string, productId: string, retailerId: string, price: number): Promise<void>;
    addPickupPoint(id: string, name: string, townId: string, address: string, profileImageUrl: string | null): Promise<void>;
    addProduct(id: string, name: string, description: string, category: string, imageEmoji: string, imagesJson: string | null, isSpecial: boolean, serviceFee: number): Promise<void>;
    addRetailer(id: string, name: string, townId: string, businessAreaId: string, address: string, operatingHoursJson: string | null): Promise<void>;
    addRetailerProduct(id: string, retailerId: string, name: string, description: string, category: string, price: number, imageEmoji: string, imagesJson: string | null): Promise<void>;
    /**
     * / *********************************************************
     * /    * Persistence API Endpoints
     * /   ***********************************************************
     */
    addTown(id: string, name: string, province: string): Promise<void>;
    approveSuggestion(id: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignShopperToRetailer(shopperPrincipal: Principal, retailerId: string): Promise<void>;
    deleteBusinessArea(id: string): Promise<void>;
    deleteListing(id: string): Promise<void>;
    deleteOrder(id: string): Promise<void>;
    deletePickupPoint(id: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    deleteRetailer(id: string): Promise<void>;
    deleteRetailerProduct(id: string): Promise<void>;
    deleteTown(id: string): Promise<void>;
    getAllShopperAssignments(): Promise<Array<[Principal, Array<string>]>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getBusinessAreas(): Promise<Array<BusinessArea>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getListings(): Promise<Array<ProductListing>>;
    getMyOrders(customerId: string): Promise<Array<Order>>;
    getMyProfile(): Promise<UserProfile | null>;
    getOrderById(id: string): Promise<Order | null>;
    getOrders(): Promise<Array<Order>>;
    getOrdersByArea(businessAreaId: string): Promise<Array<Order>>;
    getOrdersByCustomerId(customerId: string): Promise<Array<Order>>;
    getOrdersByStatus(statusText: string): Promise<Array<Order>>;
    getPickupPoints(): Promise<Array<PickupPoint>>;
    getProducts(): Promise<Array<Product>>;
    getRetailerProducts(): Promise<Array<RetailerProduct>>;
    getRetailers(): Promise<Array<Retailer>>;
    getShopperRetailerIds(shopperPrincipal: Principal): Promise<Array<string>>;
    getStaffBusinessArea(staffPrincipal: Principal): Promise<string | null>;
    getTowns(): Promise<Array<Town>>;
    getUserCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasAnyAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    placeOrder(id: string, customerId: string, customerName: string, customerPhone: string, itemsJson: string, total: number, deliveryType: string, pickupPointId: string, pickupPointName: string, homeAddress: string | null, townId: string, businessAreaId: string, deliveryAreasJson: string | null, createdAt: string, isWalkIn: boolean, parentOrderId: string | null, dedicatedRetailerId: string | null): Promise<void>;
    registerUser(role: AppUserRole, displayName: string, phone: string, businessAreaId: string | null): Promise<void>;
    rejectSuggestion(id: string): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(displayName: string, phone: string, businessAreaId: string | null): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setListingStock(id: string, outOfStock: boolean): Promise<void>;
    setRetailerProductStock(id: string, inStock: boolean): Promise<void>;
    suggestProduct(id: string, name: string, description: string, category: string, imageEmoji: string, suggestedBy: string): Promise<void>;
    unassignShopperFromRetailer(shopperPrincipal: Principal, retailerId: string): Promise<void>;
    updateOrderStatus(id: string, statusText: string, shopperId: string | null, shopperName: string | null, driverId: string | null, driverName: string | null, updatedAt: string): Promise<void>;
    updateListingPrice(id: string, price: number): Promise<void>;
    updatePickupPoint(id: string, name: string, address: string, profileImageUrl: string | null): Promise<void>;
    updateProduct(id: string, name: string, description: string, category: string, imageEmoji: string, imagesJson: string | null, isSpecial: boolean, serviceFee: number): Promise<void>;
    updateRetailerHours(id: string, operatingHoursJson: string): Promise<void>;
    updateRetailerProduct(id: string, name: string, description: string, category: string, price: number, imageEmoji: string, imagesJson: string | null): Promise<void>;
    getNomayiniBalance(): Promise<{ totalEarned: number; unlockedBalance: number; lockedShortTerm: number; lockedLongTerm: number }>;
    getNomayiniTransactions(): Promise<Array<{ id: string; txType: string; amount: number; description: string; date: string; unlockDate?: string }>>;
    sendNomayiniTokens(recipientPhone: string, amount: number, now: string): Promise<void>;
    addCategory(name: string): Promise<void>;
    getCategories(): Promise<Array<string>>;
}
import type { AppUserRole as _AppUserRole, ApprovalStatus as _ApprovalStatus, Order as _Order, PickupPoint as _PickupPoint, Product as _Product, Retailer as _Retailer, RetailerProduct as _RetailerProduct, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBusinessArea(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBusinessArea(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBusinessArea(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addListing(arg0: string, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addListing(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addListing(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPickupPoint(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPickupPoint(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPickupPoint(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: boolean, arg7: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async addRetailer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRetailer(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRetailer(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addRetailerProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: string, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRetailerProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRetailerProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async addTown(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTown(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTown(arg0, arg1, arg2);
            return result;
        }
    }
    async approveSuggestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveSuggestion(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignShopperToRetailer(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignShopperToRetailer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignShopperToRetailer(arg0, arg1);
            return result;
        }
    }
    async deleteBusinessArea(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBusinessArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBusinessArea(arg0);
            return result;
        }
    }
    async deleteListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deletePickupPoint(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePickupPoint(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePickupPoint(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteRetailer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRetailer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRetailer(arg0);
            return result;
        }
    }
    async deleteRetailerProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRetailerProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRetailerProduct(arg0);
            return result;
        }
    }
    async deleteTown(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTown(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTown(arg0);
            return result;
        }
    }
    async getAllShopperAssignments(): Promise<Array<[Principal, Array<string>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShopperAssignments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShopperAssignments();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusinessAreas(): Promise<Array<BusinessArea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessAreas();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListings(): Promise<Array<ProductListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListings();
            return result;
        }
    }
    async getMyOrders(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByArea(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByArea(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByArea(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByCustomerId(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomerId(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomerId(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPickupPoints(): Promise<Array<PickupPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPickupPoints();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPickupPoints();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRetailerProducts(): Promise<Array<RetailerProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRetailerProducts();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRetailerProducts();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRetailers(): Promise<Array<Retailer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRetailers();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRetailers();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopperRetailerIds(arg0: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopperRetailerIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopperRetailerIds(arg0);
            return result;
        }
    }
    async getStaffBusinessArea(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffBusinessArea(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffBusinessArea(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTowns(): Promise<Array<Town>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTowns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTowns();
            return result;
        }
    }
    async getUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasAnyAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAnyAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAnyAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: string, arg7: string, arg8: string, arg9: string | null, arg10: string, arg11: string, arg12: string | null, arg13: string, arg14: boolean, arg15: string | null, arg16: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg9), arg10, arg11, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg12), arg13, arg14, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg16));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg9), arg10, arg11, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg12), arg13, arg14, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg16));
            return result;
        }
    }
    async registerUser(arg0: AppUserRole, arg1: string, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_AppUserRole_n42(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_AppUserRole_n42(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async rejectSuggestion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectSuggestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectSuggestion(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setListingStock(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setListingStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setListingStock(arg0, arg1);
            return result;
        }
    }
    async setRetailerProductStock(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRetailerProductStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRetailerProductStock(arg0, arg1);
            return result;
        }
    }
    async suggestProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suggestProduct(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suggestProduct(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async unassignShopperFromRetailer(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unassignShopperFromRetailer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unassignShopperFromRetailer(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateRetailerHours(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRetailerHours(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRetailerHours(arg0, arg1);
            return result;
        }
    }
    async updateListingPrice(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListingPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListingPrice(arg0, arg1);
            return result;
        }
    }
    async updatePickupPoint(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePickupPoint(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePickupPoint(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string | null, arg6: boolean, arg7: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async updateRetailerProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: string, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRetailerProduct(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRetailerProduct(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async getNomayiniBalance(): Promise<{ totalEarned: number; unlockedBalance: number; lockedShortTerm: number; lockedLongTerm: number }> {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const actor = this.actor as any;
        const result = await actor.getNomayiniBalance();
        return { totalEarned: Number(result.totalEarned), unlockedBalance: Number(result.unlockedBalance), lockedShortTerm: Number(result.lockedShortTerm), lockedLongTerm: Number(result.lockedLongTerm) };
    }
    async getNomayiniTransactions(): Promise<Array<{ id: string; txType: string; amount: number; description: string; date: string; unlockDate?: string }>> {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const actor = this.actor as any;
        const result = await actor.getNomayiniTransactions();
        return (result as any[]).map((tx: any) => ({
            id: String(tx.id),
            txType: String(tx.txType),
            amount: Number(tx.amount),
            description: String(tx.description),
            date: String(tx.date),
            unlockDate: tx.unlockDate?.[0] ? String(tx.unlockDate[0]) : undefined,
        }));
    }
    async sendNomayiniTokens(recipientPhone: string, amount: number, now: string): Promise<void> {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const actor = this.actor as any;
        await actor.sendNomayiniTokens(recipientPhone, amount, now);
    }
    async addCategory(name: string): Promise<void> {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const actor = this.actor as any;
        await actor.addCategory(name);
    }
    async getCategories(): Promise<Array<string>> {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const actor = this.actor as any;
        return actor.getCategories();
    }

    async addArticle(id: string, title: string, body: string, categoryId: string, imagesJson: string | null, published: boolean): Promise<void> {
        const actor = this.actor as any;
        await actor.addArticle(id, title, body, categoryId, imagesJson ? [imagesJson] : [], published);
    }
    async updateArticle(id: string, title: string, body: string, categoryId: string, imagesJson: string | null, published: boolean): Promise<void> {
        const actor = this.actor as any;
        await actor.updateArticle(id, title, body, categoryId, imagesJson ? [imagesJson] : [], published);
    }
    async deleteArticle(id: string): Promise<void> {
        const actor = this.actor as any;
        await actor.deleteArticle(id);
    }
    async getArticles(): Promise<Array<{ id: string; title: string; body: string; categoryId: string; imagesJson: string | null; authorPrincipal: string; createdAt: number; published: boolean }>> {
        const actor = this.actor as any;
        const raw = await actor.getArticles();
        return raw.map((a: any) => ({
            id: a.id,
            title: a.title,
            body: a.body,
            categoryId: a.categoryId,
            imagesJson: a.imagesJson.length > 0 ? a.imagesJson[0] : null,
            authorPrincipal: a.authorPrincipal.toString(),
            createdAt: Number(a.createdAt),
            published: a.published,
        }));
    }
    async addArticleCategory(id: string, name: string): Promise<void> {
        const actor = this.actor as any;
        await actor.addArticleCategory(id, name);
    }
    async getArticleCategories(): Promise<Array<{ id: string; name: string }>> {
        const actor = this.actor as any;
        return actor.getArticleCategories();
    }
    async addReview(id: string, targetId: string, targetType: string, rating: number, comment: string, orderId: string): Promise<void> {
        const actor = this.actor as any;
        await actor.addReview(id, targetId, targetType, BigInt(rating), comment, orderId);
    }
    async getReviewsForTarget(targetId: string): Promise<Array<{ id: string; targetId: string; targetType: string; reviewerId: string; rating: number; comment: string; orderId: string; createdAt: number }>> {
        const actor = this.actor as any;
        const raw = await actor.getReviewsForTarget(targetId);
        return raw.map((r: any) => ({
            id: r.id,
            targetId: r.targetId,
            targetType: r.targetType,
            reviewerId: r.reviewerId.toString(),
            rating: Number(r.rating),
            comment: r.comment,
            orderId: r.orderId,
            createdAt: Number(r.createdAt),
        }));
    }
    async setLikeDislike(targetId: string, targetType: string, isLike: boolean): Promise<void> {
        const actor = this.actor as any;
        await actor.setLikeDislike(targetId, targetType, isLike);
    }
    async getLikesDislikesForTarget(targetId: string): Promise<Array<{ targetId: string; targetType: string; userId: string; isLike: boolean }>> {
        const actor = this.actor as any;
        const raw = await actor.getLikesDislikesForTarget(targetId);
        return raw.map((l: any) => ({
            targetId: l.targetId,
            targetType: l.targetType,
            userId: l.userId.toString(),
            isLike: l.isLike,
        }));
    }
}
function from_candid_AppUserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserRole): AppUserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PickupPoint_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PickupPoint): PickupPoint {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_RetailerProduct_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RetailerProduct): RetailerProduct {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Retailer_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Retailer): Retailer {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: string;
    role: _AppUserRole;
    phone: string;
    registrationStatus: {
        active: null;
    } | {
        pending: null;
    } | {
        updateNeeded: null;
    } | {
        rejected: null;
    };
    registeredAt: bigint;
    businessAreaId: [] | [string];
}): {
    principal: Principal;
    displayName: string;
    role: AppUserRole;
    phone: string;
    registrationStatus: Variant_active_pending_updateNeeded_rejected;
    registeredAt: bigint;
    businessAreaId?: string;
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        role: from_candid_AppUserRole_n14(_uploadFile, _downloadFile, value.role),
        phone: value.phone,
        registrationStatus: from_candid_variant_n16(_uploadFile, _downloadFile, value.registrationStatus),
        registeredAt: value.registeredAt,
        businessAreaId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.businessAreaId))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: string;
    driverId: [] | [string];
    isWalkIn: boolean;
    total: number;
    customerPhone: string;
    pickupPointId: string;
    pickupPointName: string;
    dedicatedRetailerId: [] | [string];
    createdAt: string;
    deliveryType: string;
    deliveryAreasJson: [] | [string];
    parentOrderId: [] | [string];
    updatedAt: string;
    homeAddress: [] | [string];
    shopperId: [] | [string];
    townId: string;
    customerId: string;
    itemsJson: string;
    driverName: [] | [string];
    businessAreaId: string;
    shopperName: [] | [string];
}): {
    id: string;
    customerName: string;
    status: string;
    driverId?: string;
    isWalkIn: boolean;
    total: number;
    customerPhone: string;
    pickupPointId: string;
    pickupPointName: string;
    dedicatedRetailerId?: string;
    createdAt: string;
    deliveryType: string;
    deliveryAreasJson?: string;
    parentOrderId?: string;
    updatedAt: string;
    homeAddress?: string;
    shopperId?: string;
    townId: string;
    customerId: string;
    itemsJson: string;
    driverName?: string;
    businessAreaId: string;
    shopperName?: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: value.status,
        driverId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.driverId)),
        isWalkIn: value.isWalkIn,
        total: value.total,
        customerPhone: value.customerPhone,
        pickupPointId: value.pickupPointId,
        pickupPointName: value.pickupPointName,
        dedicatedRetailerId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.dedicatedRetailerId)),
        createdAt: value.createdAt,
        deliveryType: value.deliveryType,
        deliveryAreasJson: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.deliveryAreasJson)),
        parentOrderId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.parentOrderId)),
        updatedAt: value.updatedAt,
        homeAddress: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.homeAddress)),
        shopperId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.shopperId)),
        townId: value.townId,
        customerId: value.customerId,
        itemsJson: value.itemsJson,
        driverName: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.driverName)),
        businessAreaId: value.businessAreaId,
        shopperName: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.shopperName))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    townId: string;
    address: string;
    profileImageUrl: [] | [string];
}): {
    id: string;
    name: string;
    townId: string;
    address: string;
    profileImageUrl?: string;
} {
    return {
        id: value.id,
        name: value.name,
        townId: value.townId,
        address: value.address,
        profileImageUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.profileImageUrl))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    suggestedBy: [] | [string];
    inStock: boolean;
    isSuggestion: boolean;
    name: string;
    description: string;
    imageEmoji: string;
    approved: boolean;
    category: string;
    imagesJson: [] | [string];
    isSpecial: boolean;
    serviceFee: number;
}): {
    id: string;
    suggestedBy?: string;
    inStock: boolean;
    isSuggestion: boolean;
    name: string;
    description: string;
    imageEmoji: string;
    approved: boolean;
    category: string;
    imagesJson?: string;
    isSpecial: boolean;
    serviceFee: number;
} {
    return {
        id: value.id,
        suggestedBy: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.suggestedBy)),
        inStock: value.inStock,
        isSuggestion: value.isSuggestion,
        name: value.name,
        description: value.description,
        imageEmoji: value.imageEmoji,
        approved: value.approved,
        category: value.category,
        imagesJson: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.imagesJson)),
        isSpecial: value.isSpecial ?? false,
        serviceFee: value.serviceFee ?? 0
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    inStock: boolean;
    name: string;
    description: string;
    imageEmoji: string;
    category: string;
    price: number;
    imagesJson: [] | [string];
    retailerId: string;
}): {
    id: string;
    inStock: boolean;
    name: string;
    description: string;
    imageEmoji: string;
    category: string;
    price: number;
    imagesJson?: string;
    retailerId: string;
} {
    return {
        id: value.id,
        inStock: value.inStock,
        name: value.name,
        description: value.description,
        imageEmoji: value.imageEmoji,
        category: value.category,
        price: value.price,
        imagesJson: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.imagesJson)),
        retailerId: value.retailerId
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    operatingHoursJson: [] | [string];
    townId: string;
    address: string;
    businessAreaId: string;
}): {
    id: string;
    name: string;
    operatingHoursJson?: string;
    townId: string;
    address: string;
    businessAreaId: string;
} {
    return {
        id: value.id,
        name: value.name,
        operatingHoursJson: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.operatingHoursJson)),
        townId: value.townId,
        address: value.address,
        businessAreaId: value.businessAreaId
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n40(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    operator: null;
} | {
    shopper: null;
} | {
    driver: null;
}): AppUserRole {
    return "admin" in value ? AppUserRole.admin : "customer" in value ? AppUserRole.customer : "operator" in value ? AppUserRole.operator : "shopper" in value ? AppUserRole.shopper : "driver" in value ? AppUserRole.driver : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    updateNeeded: null;
} | {
    rejected: null;
}): Variant_active_pending_updateNeeded_rejected {
    return "active" in value ? Variant_active_pending_updateNeeded_rejected.active : "pending" in value ? Variant_active_pending_updateNeeded_rejected.pending : "updateNeeded" in value ? Variant_active_pending_updateNeeded_rejected.updateNeeded : "rejected" in value ? Variant_active_pending_updateNeeded_rejected.rejected : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PickupPoint>): Array<PickupPoint> {
    return value.map((x)=>from_candid_PickupPoint_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RetailerProduct>): Array<RetailerProduct> {
    return value.map((x)=>from_candid_RetailerProduct_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Retailer>): Array<Retailer> {
    return value.map((x)=>from_candid_Retailer_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n38(_uploadFile, _downloadFile, x));
}
function to_candid_AppUserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): _AppUserRole {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): {
    admin: null;
} | {
    customer: null;
} | {
    operator: null;
} | {
    shopper: null;
} | {
    driver: null;
} {
    return value == AppUserRole.admin ? {
        admin: null
    } : value == AppUserRole.customer ? {
        customer: null
    } : value == AppUserRole.operator ? {
        operator: null
    } : value == AppUserRole.shopper ? {
        shopper: null
    } : value == AppUserRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
